// Required subset of Dylan's supplied garden toolbox; no garden or café gameplay.
import * as THREE from 'three';
import {mergeGeometries} from 'three/addons/utils/BufferGeometryUtils.js';
export {THREE};
export const TAU=Math.PI*2,clamp=THREE.MathUtils.clamp,lerp=THREE.MathUtils.lerp;
export const smooth=t=>t*t*(3-2*t),ease=(rate,dt)=>1-Math.pow(1-rate,dt*60);
export function rng(seed=1){let s=(seed>>>0)||1;return ()=>(s=(Math.imul(s,1664525)+1013904223)>>>0)/4294967296;}
export const GEO={box:new THREE.BoxGeometry(1,1,1),sphere:new THREE.SphereGeometry(1,20,14),lowSphere:new THREE.SphereGeometry(1,10,7),hemi:new THREE.SphereGeometry(1,20,10,0,TAU,0,Math.PI/2),cyl:new THREE.CylinderGeometry(1,1,1,16),lowCyl:new THREE.CylinderGeometry(1,1,1,8),cone:new THREE.ConeGeometry(1,1,16),torus:new THREE.TorusGeometry(1,.25,10,24),capsule:new THREE.CapsuleGeometry(.5,1,6,12),plane:new THREE.PlaneGeometry(1,1),circle:new THREE.CircleGeometry(1,28)};
const shared=new Set(Object.values(GEO)),materials=new Map();
export function mat(color,options={}){const key=JSON.stringify([color,options]);if(!materials.has(key))materials.set(key,new THREE.MeshStandardMaterial({color,roughness:.8,...options}));return materials.get(key);}
export function mesh(geo,material,parent,pos=[0,0,0],scale=[1,1,1],rot=[0,0,0]){const m=new THREE.Mesh(geo,typeof material==='string'||typeof material==='number'?mat(material):material);m.position.set(...pos);m.scale.set(...scale);m.rotation.set(...rot);m.castShadow=true;m.receiveShadow=true;parent?.add(m);return m;}
export function canvasTexture(width,height,draw,{repeat=null,srgb=true}={}){const c=Object.assign(document.createElement('canvas'),{width,height});draw(c.getContext('2d'),width,height);const t=new THREE.CanvasTexture(c);if(srgb)t.colorSpace=THREE.SRGBColorSpace;if(repeat){t.wrapS=t.wrapT=THREE.RepeatWrapping;t.repeat.set(...repeat);}t.anisotropy=4;return t;}
let blob;
export function shadowBlob(radius=.5,opacity=.35){blob??=canvasTexture(64,64,(g,w,h)=>{const gradient=g.createRadialGradient(w/2,h/2,0,w/2,h/2,w/2);gradient.addColorStop(0,'rgba(0,0,0,1)');gradient.addColorStop(.55,'rgba(0,0,0,.45)');gradient.addColorStop(1,'rgba(0,0,0,0)');g.fillStyle=gradient;g.fillRect(0,0,w,h);},{srgb:false});const m=new THREE.Mesh(GEO.plane,new THREE.MeshBasicMaterial({map:blob,transparent:true,opacity,depthWrite:false,color:0x2a3a2c}));m.rotation.x=-Math.PI/2;m.scale.set(radius*2,radius*2,1);m.position.y=.015;return m;}
export function mergeStatic(root){root.updateMatrixWorld(true);const inverse=root.matrixWorld.clone().invert(),buckets=new Map();root.traverse(n=>{if(!n.isMesh||Array.isArray(n.material))return;const g=n.geometry.index?n.geometry.toNonIndexed():n.geometry.clone();g.applyMatrix4(new THREE.Matrix4().multiplyMatrices(inverse,n.matrixWorld));for(const key of Object.keys(g.attributes))if(!['position','normal','uv'].includes(key))g.deleteAttribute(key);if(!g.attributes.uv)g.setAttribute('uv',new THREE.Float32BufferAttribute(new Float32Array(g.attributes.position.count*2),2));if(!g.attributes.normal)g.computeVertexNormals();const key=n.material.uuid;if(!buckets.has(key))buckets.set(key,{material:n.material,list:[]});buckets.get(key).list.push(g);});const result=new THREE.Group();for(const {material,list}of buckets.values()){const g=mergeGeometries(list,false);for(const x of list)x.dispose();if(!g)continue;const m=new THREE.Mesh(g,material);m.castShadow=true;m.receiveShadow=true;result.add(m);}return result;}
export function disposeTree(root){root.traverse(n=>{if(n.geometry&&!shared.has(n.geometry)&&!n.geometry.userData.shared)n.geometry.dispose();});}
